if(new URLSearchParams(location.search).get('embedded')==='1') document.body.classList.add('bast-embedded');
const STORAGE_KEY=window.BastComptaStorageKeys?.suppliers || 'bastcompta-fournisseurs-v1';
const DEVIS_STORAGE_KEY=window.BastComptaStorageKeys?.documents || 'devis-facture-style-vrai-document';
const DRIVE_SYNC_FILE_NAME='bastcompta-fournisseurs-sync.json';
let googleAccessToken=null, selectedSupplierId='', selectedTab='info', driveSaveTimer=null;
const uid=p=>BastFileUtils.createId(p,{separator:'_',randomLength:5});
const num=BastFormatters.number;
const esc=BastFormatters.escapeHtml;
const money=BastFormatters.money;
const EXCEL_KEYS=['reference','nom_article','prix_brut','remise_pct','prix_net','prix_vente','unite','tva_pct','notes'];
const EXCEL_REQUIRED_KEYS=['nom_article'];
function excelReady(){if(window.XLSX)return true;notify('Le module Excel n’est pas encore chargé. Réessaie dans un instant.');return false}
function safeFilePart(v){return BastFileUtils.safeNamePart(v,'fournisseur',60)}
function importNumber(v){if(typeof v==='number'&&Number.isFinite(v))return v;let t=String(v??'').trim();if(!t)return 0;t=t.replace(/\s/g,'').replace(/€/g,'').replace(/%/g,'').replace(',','.');const n=Number(t);return Number.isFinite(n)?n:0}
function articleToExcelRow(a){return{reference:a.reference||'',nom_article:a.name||'',prix_brut:num(a.grossPrice),remise_pct:num(a.discountPct),prix_net:netPrice(a),prix_vente:num(a.salePrice),unite:a.unit||'p',tva_pct:num(a.vatRate)||21,notes:a.notes||''}}
function styleExcelSheet(ws,rowCount){ws['!cols']=[{wch:18},{wch:34},{wch:14},{wch:13},{wch:14},{wch:14},{wch:10},{wch:10},{wch:36}];ws['!autofilter']={ref:`A1:I${Math.max(1,rowCount+1)}`};for(let r=2;r<=rowCount+1;r++){['C','D','E','F','H'].forEach(c=>{if(ws[`${c}${r}`])ws[`${c}${r}`].z=c==='D'||c==='H'?'0.00':'0.00 [$€-fr-BE]'})}}
function createInstructionSheet(){const rows=[['IMPORT ARTICLES FOURNISSEUR'],[''],['Clés attendues (ligne 1 du fichier)'],...EXCEL_KEYS.map(k=>[k,EXCEL_REQUIRED_KEYS.includes(k)?'OBLIGATOIRE':'optionnel']),[''],['Règles'],['nom_article','Nom de l’article. Obligatoire.'],['reference','Référence fournisseur. Si elle existe déjà, l’article correspondant sera mis à jour.'],['prix_brut','Prix brut fournisseur, hors TVA.'],['remise_pct','Remise en pourcentage. Exemple : 12,5 pour 12,5 %.'],['prix_net','Calculé par BastCompta. Cette colonne est ignorée à l’import.'],['prix_vente','Prix de vente hors TVA.'],['unite','Exemples : p, h, m, m², kg.'],['tva_pct','Taux de TVA. Exemple : 21.'],['notes','Texte libre.'],[''],['Import','Les lignes sont ajoutées au fournisseur actuellement sélectionné. Une référence déjà existante est mise à jour ; sans référence, BastCompta cherche un nom d’article identique.']];const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:24},{wch:90}];return ws}
function downloadArticleModel(){if(!excelReady())return;const wb=XLSX.utils.book_new();const sample=[{reference:'REF-001',nom_article:'Exemple article',prix_brut:100,remise_pct:10,prix_net:90,prix_vente:125,unite:'p',tva_pct:21,notes:'Supprime cette ligne avant import'}];const ws=XLSX.utils.json_to_sheet(sample,{header:EXCEL_KEYS});styleExcelSheet(ws,sample.length);XLSX.utils.book_append_sheet(wb,ws,'Articles');XLSX.utils.book_append_sheet(wb,createInstructionSheet(),'Instructions');XLSX.writeFile(wb,'Modele_import_articles_BastCompta.xlsx')}
function exportArticlesExcel(){const s=supplier();if(!s)return notify('Sélectionne d’abord un fournisseur.');if(!excelReady())return;const rows=s.articles.map(articleToExcelRow);const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows,{header:EXCEL_KEYS});styleExcelSheet(ws,rows.length);XLSX.utils.book_append_sheet(wb,ws,'Articles');XLSX.utils.book_append_sheet(wb,createInstructionSheet(),'Instructions');XLSX.writeFile(wb,`Articles_${safeFilePart(s.name)}.xlsx`);notify(`${rows.length} article${rows.length!==1?'s':''} exporté${rows.length!==1?'s':''}.`)}
function chooseArticlesExcel(){const s=supplier();if(!s)return notify('Sélectionne d’abord un fournisseur.');if(!excelReady())return;document.getElementById('articleExcelInput')?.click()}
async function importArticlesExcel(file){if(!file)return;const s=supplier();if(!s)return notify('Sélectionne d’abord un fournisseur.');if(!excelReady())return;try{const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:'array'});const ws=wb.Sheets.Articles||wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('Aucune feuille à importer.');const rows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});if(!rows.length)return notify('Le fichier Excel ne contient aucune ligne.');const headers=Object.keys(rows[0]).map(x=>String(x).trim());const missing=EXCEL_REQUIRED_KEYS.filter(k=>!headers.includes(k));if(missing.length){alert(`Import impossible. Clé obligatoire manquante : ${missing.join(', ')}.\n\nTélécharge le modèle Excel depuis BastCompta pour obtenir les bonnes clés.`);return}let added=0,updated=0,skipped=0;for(const row of rows){const name=String(row.nom_article??'').trim();if(!name||/^exemple article$/i.test(name)){skipped++;continue}const reference=String(row.reference??'').trim();let a=reference?s.articles.find(x=>String(x.reference||'').trim().toLowerCase()===reference.toLowerCase()):null;if(!a)a=s.articles.find(x=>String(x.name||'').trim().toLowerCase()===name.toLowerCase());const values={reference,name,grossPrice:importNumber(row.prix_brut),discountPct:importNumber(row.remise_pct),salePrice:importNumber(row.prix_vente),unit:String(row.unite??'').trim()||'p',vatRate:importNumber(row.tva_pct)||21,notes:String(row.notes??'').trim()};if(a){Object.assign(a,values);updated++}else{s.articles.push(normalizeArticle(values));added++}}saveLocal('Import Excel articles fournisseur');selectedTab='articles';renderWorkspace();renderSupplierList();notify(`Import terminé : ${added} ajouté${added!==1?'s':''}, ${updated} mis à jour${updated!==1?'s':''}${skipped?`, ${skipped} ignoré${skipped!==1?'s':''}`:''}.`)}catch(e){console.error(e);alert('Impossible de lire ce fichier Excel. Utilise de préférence le modèle téléchargé depuis BastCompta (.xlsx).')}}
function blankData(){return{version:1,updatedAt:new Date().toISOString(),suppliers:[]}}
function normalizeArticle(a={}){return BastSupplierModel.normalizeArticle(a,()=>uid('article'))}
function normalizeSupplier(s={}){return BastSupplierModel.normalizeSupplier(s,{createId:()=>uid('supplier'),createArticleId:()=>uid('article')})}
function normalizeData(d){return BastSupplierModel.normalizeData(d,{createId:()=>uid('supplier'),createArticleId:()=>uid('article'),now:()=>new Date().toISOString()})}
function loadData(){return normalizeData(BastFileUtils.parseJson(localStorage.getItem(STORAGE_KEY),null))}
let data=loadData();
function saveLocal(detail='Fournisseurs modifiés'){data.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));try{window.parent?.BastComptaPortal?.markChanged?.('fournisseurs',detail)}catch{};if(googleAccessToken){clearTimeout(driveSaveTimer);driveSaveTimer=setTimeout(()=>saveSyncToDrive(false),900)}}
function notify(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function supplier(){return data.suppliers.find(s=>s.id===selectedSupplierId)||null}
function returnToDevis(page='tarifs'){if(window.parent&&window.parent!==window){safePostToParent({type:'BASTCOMPTA_OPEN_DEVIS_PAGE',pageKey:page});return}location.href=`devis-facture.html?embedded=1&open=${encodeURIComponent(page)}`}
function addSupplier(){const s=normalizeSupplier({name:'Nouveau fournisseur'});data.suppliers.unshift(s);selectedSupplierId=s.id;selectedTab='info';saveLocal('Fournisseur ajouté');renderAll()}
async function deleteSupplier(){const s=supplier();if(!s||!await BastUI.confirm(`Placer « ${s.name||'ce fournisseur'} » et ses articles dans la corbeille ?`,{type:'danger',title:'Mettre le fournisseur à la corbeille',confirmLabel:'Mettre à la corbeille'}))return;BastTrash.add({module:'Fournisseurs',type:'Fournisseur',label:s.name||'Fournisseur',storageKey:STORAGE_KEY,path:['suppliers'],item:s});data.suppliers=data.suppliers.filter(x=>x.id!==s.id);selectedSupplierId='';saveLocal('Fournisseur placé dans la corbeille');renderAll()}
function setField(k,v){const s=supplier();if(!s)return;s[k]=v;saveLocal('Fiche fournisseur modifiée');renderSupplierList()}
function setTab(t){selectedTab=t;renderWorkspace()}
function addArticle(){const s=supplier();if(!s)return;s.articles.push(normalizeArticle({}));saveLocal('Article fournisseur ajouté');renderWorkspace()}
function deleteArticle(id){const s=supplier();if(!s)return;s.articles=s.articles.filter(a=>a.id!==id);saveLocal('Article fournisseur supprimé');renderWorkspace()}
function updateArticle(id,k,v){const a=supplier()?.articles.find(x=>x.id===id);if(!a)return;a[k]=['grossPrice','discountPct','salePrice','vatRate'].includes(k)?num(v):v;saveLocal('Article fournisseur modifié');if(k==='grossPrice'||k==='discountPct')refreshNet(id)}
function netPrice(a){return BastSupplierModel.netPrice(a)}
function refreshNet(id){const a=supplier()?.articles.find(x=>x.id===id);const e=document.querySelector(`[data-net="${id}"]`);if(a&&e)e.textContent=money(netPrice(a))}
function renderSupplierList(){const q=(document.getElementById('supplierSearch')?.value||'').toLowerCase();const rows=data.suppliers.filter(s=>`${s.name} ${s.vat} ${s.contact}`.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'fr'));document.getElementById('supplierCount').textContent=data.suppliers.length;document.getElementById('supplierList').innerHTML=rows.length?rows.map(s=>`<button class="supplier-item ${s.id===selectedSupplierId?'active':''}" onclick="selectSupplier('${s.id}')"><strong>${esc(s.name||'Sans nom')}</strong><span>${esc(s.vat||'TVA non renseignée')} · ${s.articles.length} article${s.articles.length!==1?'s':''}</span></button>`).join(''):'<div class="empty" style="min-height:220px"><div>Aucun fournisseur.</div></div>'}
function selectSupplier(id){selectedSupplierId=id;selectedTab='info';renderSupplierList();renderWorkspace()}
function infoHtml(s){return `<div class="form-grid"><div class="field"><label>Nom du fournisseur</label><input value="${esc(s.name)}" oninput="setField('name',this.value)"></div><div class="field"><label>N° TVA</label><input value="${esc(s.vat)}" oninput="setField('vat',this.value)"></div><div class="field"><label>Personne de contact</label><input value="${esc(s.contact)}" oninput="setField('contact',this.value)"></div><div class="field"><label>E-mail</label><input type="email" value="${esc(s.email)}" oninput="setField('email',this.value)"></div><div class="field"><label>Téléphone</label><input value="${esc(s.phone)}" oninput="setField('phone',this.value)"></div><div class="field"><label>Site internet</label><input value="${esc(s.website)}" oninput="setField('website',this.value)"></div><div class="field full"><label>Adresse</label><input value="${esc(s.address)}" oninput="setField('address',this.value)"></div><div class="field"><label>Conditions de paiement</label><input value="${esc(s.paymentTerms)}" oninput="setField('paymentTerms',this.value)" placeholder="30 jours, comptant..."></div><div class="field full"><label>Notes</label><textarea oninput="setField('notes',this.value)">${esc(s.notes)}</textarea></div></div>`}
function articlesHtml(s){return `<div class="articles-head"><div><h3>Articles du fournisseur</h3><small>${s.articles.length} article${s.articles.length!==1?'s':''}</small></div><div class="article-toolbar"><button class="secondary" onclick="downloadArticleModel()">Modèle Excel</button><button class="secondary" onclick="chooseArticlesExcel()">Importer Excel</button><button class="secondary" onclick="exportArticlesExcel()">Exporter Excel</button><button class="primary" onclick="addArticle()">+ Ajouter un article</button></div></div><div class="excel-hint">Import Excel : utilise le modèle BastCompta. Les clés reconnues sont <strong>reference, nom_article, prix_brut, remise_pct, prix_net, prix_vente, unite, tva_pct, notes</strong>. Le prix net est recalculé automatiquement.</div><div class="table-wrap"><table class="article-table"><thead><tr><th>Référence</th><th>Nom de l'article</th><th>Prix brut</th><th>Remise %</th><th>Prix net</th><th>Prix de vente</th><th>Unité</th><th>TVA %</th><th>Actions</th></tr></thead><tbody>${s.articles.length?s.articles.map(a=>`<tr><td><input value="${esc(a.reference)}" oninput="updateArticle('${a.id}','reference',this.value)"></td><td><input value="${esc(a.name)}" oninput="updateArticle('${a.id}','name',this.value)"></td><td><input inputmode="decimal" value="${a.grossPrice||''}" oninput="updateArticle('${a.id}','grossPrice',this.value)"></td><td><input inputmode="decimal" value="${a.discountPct||''}" oninput="updateArticle('${a.id}','discountPct',this.value)"></td><td class="money-cell" data-net="${a.id}">${money(netPrice(a))}</td><td><input inputmode="decimal" value="${a.salePrice||''}" oninput="updateArticle('${a.id}','salePrice',this.value)"></td><td><input value="${esc(a.unit)}" oninput="updateArticle('${a.id}','unit',this.value)"></td><td><input inputmode="decimal" value="${a.vatRate}" oninput="updateArticle('${a.id}','vatRate',this.value)"></td><td><div class="row-actions"><button class="small" onclick="addArticleToDocument('${a.id}','quote')">+ Devis</button><button class="small" onclick="addArticleToDocument('${a.id}','invoice')">+ Facture</button><button class="small danger" onclick="deleteArticle('${a.id}')">Suppr.</button></div></td></tr>`).join(''):'<tr><td colspan="9" style="text-align:center;color:#7a8494;padding:28px">Aucun article. Ajoute les articles que tu utilises régulièrement chez ce fournisseur ou importe-les avec le modèle Excel.</td></tr>'}</tbody></table></div>`}
function renderWorkspace(){const w=document.getElementById('workspace'),s=supplier();if(!s){w.innerHTML='<div class="workspace-card empty"><div><strong>Sélectionne un fournisseur</strong>ou crée une nouvelle fiche fournisseur.</div></div>';return}w.innerHTML=`<div class="workspace-card"><div class="workspace-head"><div><h2>${esc(s.name||'Sans nom')}</h2><p>${esc(s.vat||'N° TVA non renseigné')}${s.contact?' · '+esc(s.contact):''}</p></div><div class="actions"><button class="secondary danger" onclick="deleteSupplier()">Supprimer</button></div></div><div class="tabs"><button class="tab ${selectedTab==='info'?'active':''}" onclick="setTab('info')">Fiche fournisseur</button><button class="tab ${selectedTab==='articles'?'active':''}" onclick="setTab('articles')">Articles (${s.articles.length})</button></div>${selectedTab==='articles'?articlesHtml(s):infoHtml(s)}</div>`}
function renderAll(){renderSupplierList();renderWorkspace()}
function addArticleToDocument(articleId,docKey){const s=supplier(),a=s?.articles.find(x=>x.id===articleId);if(!a)return;if(!a.name.trim())return notify('Donne un nom à cet article.');const d=BastFileUtils.parseJson(localStorage.getItem(DEVIS_STORAGE_KEY),{});const target=docKey==='invoice'?'invoice':'quote';if(!d[target])return notify('Ouvre d’abord Devis & Facture au moins une fois.');if(!Array.isArray(d[target].lines))d[target].lines=[];d[target].lines.push({id:uid('line'),description:a.name,designation:a.name,libelle:a.name,qty:1,quantite:1,unit:a.unit||'p',unite:a.unit||'p',unitPrice:num(a.salePrice),prixUnitaire:num(a.salePrice),priceHtva:num(a.salePrice),costPrice:netPrice(a),coutRevient:netPrice(a),discount:0,remise:0,vatRate:num(a.vatRate)||21,tva:num(a.vatRate)||21,source:'fournisseurs',supplierId:s.id,supplierName:s.name,supplierArticleId:a.id});localStorage.setItem(DEVIS_STORAGE_KEY,JSON.stringify(d));try{window.parent?.BastComptaPortal?.markChanged?.('devis-facture',`Article fournisseur ajouté au ${target==='invoice'?'facture':'devis'}`)}catch{};notify(`Article ajouté ${target==='invoice'?'à la facture':'au devis'}.`);setTimeout(()=>returnToDevis(target),350)}
function safePostToParent(m){try{window.parent?.postMessage(m,window.location.origin&&window.location.origin!=='null'?window.location.origin:'*')}catch{}}
function setDriveState(ok){}
async function driveList(){try{return await BastComptaDriveClient.listFiles(googleAccessToken,{q:`name='${DRIVE_SYNC_FILE_NAME}' and trashed=false`,fields:'nextPageToken,files(id,name,modifiedTime)',orderBy:'modifiedTime desc',pageSize:10})}catch(error){if(error?.status===401){googleAccessToken=null;setDriveState(false);safePostToParent({type:'BASTCOMPTA_REFRESH_TOKEN'});return[]}throw error}}
async function saveSyncToDrive(showToast=true){if(!googleAccessToken){if(showToast)notify('Google Drive non connecté via le portail.');return false}try{const old=(await driveList())[0];await BastComptaDriveClient.uploadJson(googleAccessToken,{fileId:old?.id||'',name:DRIVE_SYNC_FILE_NAME,value:data,fields:'id,name'});if(showToast)notify('Fournisseurs sauvegardés sur Google Drive.');return true}catch(e){if(e?.status===401){googleAccessToken=null;setDriveState(false);safePostToParent({type:'BASTCOMPTA_REFRESH_TOKEN'})}console.error(e);if(showToast)notify('Sauvegarde Google Drive impossible.');return false}}
async function loadFromDriveIfNewer(){if(!googleAccessToken)return false;try{const file=(await driveList())[0];if(!file)return false;const remote=normalizeData(await BastComptaDriveClient.readFile(googleAccessToken,file.id));if(data.suppliers.length&&String(remote.updatedAt||'')<=String(data.updatedAt||''))return false;data=remote;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));selectedSupplierId='';renderAll();return true}catch(e){console.warn(e);return false}}
window.addEventListener('message',async e=>{if(location.origin&&location.origin!=='null'&&e.origin!==location.origin)return;const m=e.data||{};if(m.type==='BASTCOMPTA_GOOGLE_TOKEN'){googleAccessToken=m.accessToken||null;setDriveState(!!googleAccessToken);if(googleAccessToken)await loadFromDriveIfNewer()}if(m.type==='BASTCOMPTA_GOOGLE_LOGOUT'){googleAccessToken=null;setDriveState(false)}})
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){data=loadData();renderAll()}})
async function saveFromPortalGlobal(){
  saveLocal('Sauvegarde globale Fournisseurs');
  if(!googleAccessToken){
    return{ok:true,module:'fournisseurs',local:true,drive:false,warnings:['Google Drive non connecté']};
  }
  const drive=await saveSyncToDrive(false);
  if(!drive){
    return{ok:false,module:'fournisseurs',local:true,drive:false,message:'Sauvegarde locale effectuée, mais la sauvegarde Google Drive des fournisseurs a échoué.'};
  }
  return{ok:true,module:'fournisseurs',local:true,drive:true};
}
window.BastComptaModule={name:'Fournisseurs',save:saveFromPortalGlobal,saveData:saveFromPortalGlobal,getChangeSnapshot:()=>data,getStatus:()=>({ready:true,module:'fournisseurs'})};
setDriveState(false);renderAll();safePostToParent({type:'BASTCOMPTA_DRIVE_STATUS_REQUEST'});
