if(new URLSearchParams(location.search).get('embedded')==='1') document.body.classList.add('bast-embedded');
const STORAGE_KEY='bastcompta-fournisseurs-v1';
const DEVIS_STORAGE_KEY='devis-facture-style-vrai-document';
const DRIVE_SYNC_FILE_NAME='bastcompta-fournisseurs-sync.json';
let googleAccessToken=null, selectedSupplierId='', selectedTab='info', driveSaveTimer=null;
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const num=v=>Number(String(v??'').replace(',','.'))||0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR'}).format(num(v));
function blankData(){return{version:1,updatedAt:new Date().toISOString(),suppliers:[]}}
function normalizeArticle(a={}){return{id:a.id||uid('article'),name:a.name||'',reference:a.reference||'',grossPrice:num(a.grossPrice),discountPct:num(a.discountPct),salePrice:num(a.salePrice),unit:a.unit||'p',vatRate:num(a.vatRate)||21,notes:a.notes||''}}
function normalizeSupplier(s={}){return{id:s.id||uid('supplier'),name:s.name||'',vat:s.vat||'',contact:s.contact||'',email:s.email||'',phone:s.phone||'',address:s.address||'',website:s.website||'',paymentTerms:s.paymentTerms||'',notes:s.notes||'',articles:Array.isArray(s.articles)?s.articles.map(normalizeArticle):[]}}
function normalizeData(d){const b=blankData();if(d&&typeof d==='object')Object.assign(b,d);b.suppliers=Array.isArray(b.suppliers)?b.suppliers.map(normalizeSupplier):[];return b}
function loadData(){try{return normalizeData(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch{return blankData()}}
let data=loadData();
function saveLocal(detail='Fournisseurs modifiés'){data.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));try{window.parent?.BastComptaPortal?.markChanged?.('fournisseurs',detail)}catch{};if(googleAccessToken){clearTimeout(driveSaveTimer);driveSaveTimer=setTimeout(()=>saveSyncToDrive(false),900)}}
function notify(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function supplier(){return data.suppliers.find(s=>s.id===selectedSupplierId)||null}
function returnToDevis(page='tarifs'){location.href=`devis-facture.html?embedded=1&open=${encodeURIComponent(page)}`}
function addSupplier(){const s=normalizeSupplier({name:'Nouveau fournisseur'});data.suppliers.unshift(s);selectedSupplierId=s.id;selectedTab='info';saveLocal('Fournisseur ajouté');renderAll()}
function deleteSupplier(){const s=supplier();if(!s||!confirm(`Supprimer « ${s.name||'ce fournisseur'} » et ses articles ?`))return;data.suppliers=data.suppliers.filter(x=>x.id!==s.id);selectedSupplierId='';saveLocal('Fournisseur supprimé');renderAll()}
function setField(k,v){const s=supplier();if(!s)return;s[k]=v;saveLocal('Fiche fournisseur modifiée');renderSupplierList()}
function setTab(t){selectedTab=t;renderWorkspace()}
function addArticle(){const s=supplier();if(!s)return;s.articles.push(normalizeArticle({}));saveLocal('Article fournisseur ajouté');renderWorkspace()}
function deleteArticle(id){const s=supplier();if(!s)return;s.articles=s.articles.filter(a=>a.id!==id);saveLocal('Article fournisseur supprimé');renderWorkspace()}
function updateArticle(id,k,v){const a=supplier()?.articles.find(x=>x.id===id);if(!a)return;a[k]=['grossPrice','discountPct','salePrice','vatRate'].includes(k)?num(v):v;saveLocal('Article fournisseur modifié');if(k==='grossPrice'||k==='discountPct')refreshNet(id)}
function netPrice(a){return num(a.grossPrice)*(1-num(a.discountPct)/100)}
function refreshNet(id){const a=supplier()?.articles.find(x=>x.id===id);const e=document.querySelector(`[data-net="${id}"]`);if(a&&e)e.textContent=money(netPrice(a))}
function renderSupplierList(){const q=(document.getElementById('supplierSearch')?.value||'').toLowerCase();const rows=data.suppliers.filter(s=>`${s.name} ${s.vat} ${s.contact}`.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'fr'));document.getElementById('supplierCount').textContent=data.suppliers.length;document.getElementById('supplierList').innerHTML=rows.length?rows.map(s=>`<button class="supplier-item ${s.id===selectedSupplierId?'active':''}" onclick="selectSupplier('${s.id}')"><strong>${esc(s.name||'Sans nom')}</strong><span>${esc(s.vat||'TVA non renseignée')} · ${s.articles.length} article${s.articles.length!==1?'s':''}</span></button>`).join(''):'<div class="empty" style="min-height:220px"><div>Aucun fournisseur.</div></div>'}
function selectSupplier(id){selectedSupplierId=id;selectedTab='info';renderSupplierList();renderWorkspace()}
function infoHtml(s){return `<div class="form-grid"><div class="field"><label>Nom du fournisseur</label><input value="${esc(s.name)}" oninput="setField('name',this.value)"></div><div class="field"><label>N° TVA</label><input value="${esc(s.vat)}" oninput="setField('vat',this.value)"></div><div class="field"><label>Personne de contact</label><input value="${esc(s.contact)}" oninput="setField('contact',this.value)"></div><div class="field"><label>E-mail</label><input type="email" value="${esc(s.email)}" oninput="setField('email',this.value)"></div><div class="field"><label>Téléphone</label><input value="${esc(s.phone)}" oninput="setField('phone',this.value)"></div><div class="field"><label>Site internet</label><input value="${esc(s.website)}" oninput="setField('website',this.value)"></div><div class="field full"><label>Adresse</label><input value="${esc(s.address)}" oninput="setField('address',this.value)"></div><div class="field"><label>Conditions de paiement</label><input value="${esc(s.paymentTerms)}" oninput="setField('paymentTerms',this.value)" placeholder="30 jours, comptant..."></div><div class="field full"><label>Notes</label><textarea oninput="setField('notes',this.value)">${esc(s.notes)}</textarea></div></div>`}
function articlesHtml(s){return `<div class="articles-head"><div><h3>Articles du fournisseur</h3><small>${s.articles.length} article${s.articles.length!==1?'s':''}</small></div><button class="primary" onclick="addArticle()">+ Ajouter un article</button></div><div class="table-wrap"><table class="article-table"><thead><tr><th>Référence</th><th>Nom de l'article</th><th>Prix brut</th><th>Remise %</th><th>Prix net</th><th>Prix de vente</th><th>Unité</th><th>TVA %</th><th>Actions</th></tr></thead><tbody>${s.articles.length?s.articles.map(a=>`<tr><td><input value="${esc(a.reference)}" oninput="updateArticle('${a.id}','reference',this.value)"></td><td><input value="${esc(a.name)}" oninput="updateArticle('${a.id}','name',this.value)"></td><td><input inputmode="decimal" value="${a.grossPrice||''}" oninput="updateArticle('${a.id}','grossPrice',this.value)"></td><td><input inputmode="decimal" value="${a.discountPct||''}" oninput="updateArticle('${a.id}','discountPct',this.value)"></td><td class="money-cell" data-net="${a.id}">${money(netPrice(a))}</td><td><input inputmode="decimal" value="${a.salePrice||''}" oninput="updateArticle('${a.id}','salePrice',this.value)"></td><td><input value="${esc(a.unit)}" oninput="updateArticle('${a.id}','unit',this.value)"></td><td><input inputmode="decimal" value="${a.vatRate}" oninput="updateArticle('${a.id}','vatRate',this.value)"></td><td><div class="row-actions"><button class="small" onclick="addArticleToDocument('${a.id}','quote')">+ Devis</button><button class="small" onclick="addArticleToDocument('${a.id}','invoice')">+ Facture</button><button class="small danger" onclick="deleteArticle('${a.id}')">Suppr.</button></div></td></tr>`).join(''):'<tr><td colspan="9" style="text-align:center;color:#7a8494;padding:28px">Aucun article. Ajoute les articles que tu utilises régulièrement chez ce fournisseur.</td></tr>'}</tbody></table></div>`}
function renderWorkspace(){const w=document.getElementById('workspace'),s=supplier();if(!s){w.innerHTML='<div class="workspace-card empty"><div><strong>Sélectionne un fournisseur</strong>ou crée une nouvelle fiche fournisseur.</div></div>';return}w.innerHTML=`<div class="workspace-card"><div class="workspace-head"><div><h2>${esc(s.name||'Sans nom')}</h2><p>${esc(s.vat||'N° TVA non renseigné')}${s.contact?' · '+esc(s.contact):''}</p></div><div class="actions"><button class="secondary danger" onclick="deleteSupplier()">Supprimer</button></div></div><div class="tabs"><button class="tab ${selectedTab==='info'?'active':''}" onclick="setTab('info')">Fiche fournisseur</button><button class="tab ${selectedTab==='articles'?'active':''}" onclick="setTab('articles')">Articles (${s.articles.length})</button></div>${selectedTab==='articles'?articlesHtml(s):infoHtml(s)}</div>`}
function renderAll(){renderSupplierList();renderWorkspace()}
function addArticleToDocument(articleId,docKey){const s=supplier(),a=s?.articles.find(x=>x.id===articleId);if(!a)return;if(!a.name.trim())return notify('Donne un nom à cet article.');let d;try{d=JSON.parse(localStorage.getItem(DEVIS_STORAGE_KEY)||'{}')}catch{d={}};const target=docKey==='invoice'?'invoice':'quote';if(!d[target])return notify('Ouvre d’abord Devis & Facture au moins une fois.');if(!Array.isArray(d[target].lines))d[target].lines=[];d[target].lines.push({id:uid('line'),description:a.name,designation:a.name,libelle:a.name,qty:1,quantite:1,unit:a.unit||'p',unite:a.unit||'p',unitPrice:num(a.salePrice),prixUnitaire:num(a.salePrice),priceHtva:num(a.salePrice),costPrice:netPrice(a),coutRevient:netPrice(a),discount:0,remise:0,vatRate:num(a.vatRate)||21,tva:num(a.vatRate)||21,source:'fournisseurs',supplierId:s.id,supplierName:s.name,supplierArticleId:a.id});localStorage.setItem(DEVIS_STORAGE_KEY,JSON.stringify(d));try{window.parent?.BastComptaPortal?.markChanged?.('devis-facture',`Article fournisseur ajouté au ${target==='invoice'?'facture':'devis'}`)}catch{};notify(`Article ajouté ${target==='invoice'?'à la facture':'au devis'}.`);setTimeout(()=>returnToDevis(target),350)}
function safePostToParent(m){try{window.parent?.postMessage(m,window.location.origin&&window.location.origin!=='null'?window.location.origin:'*')}catch{}}
function setDriveState(ok){const e=document.getElementById('driveState');if(!e)return;e.textContent=`Google Drive : ${ok?'connecté':'non connecté'}`;e.classList.toggle('connected',ok)}
async function driveList(){const q=encodeURIComponent(`name='${DRIVE_SYNC_FILE_NAME}' and trashed=false`);const r=await fetch(`https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q=${q}&fields=files(id,name,modifiedTime)&orderBy=modifiedTime%20desc&pageSize=10`,{headers:{Authorization:`Bearer ${googleAccessToken}`}});if(r.status===401){googleAccessToken=null;setDriveState(false);safePostToParent({type:'BASTCOMPTA_REFRESH_TOKEN'});return[]}if(!r.ok)throw new Error('Drive list '+r.status);return(await r.json()).files||[]}
async function saveSyncToDrive(showToast=true){if(!googleAccessToken){if(showToast)notify('Google Drive non connecté via le portail.');return false}try{const old=(await driveList())[0];const metadata=old?{name:DRIVE_SYNC_FILE_NAME}:{name:DRIVE_SYNC_FILE_NAME,parents:['appDataFolder']};const f=new FormData();f.append('metadata',new Blob([JSON.stringify(metadata)],{type:'application/json'}));f.append('file',new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const url=old?`https://www.googleapis.com/upload/drive/v3/files/${old.id}?uploadType=multipart&fields=id,name`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name';const r=await fetch(url,{method:old?'PATCH':'POST',headers:{Authorization:`Bearer ${googleAccessToken}`},body:f});if(!r.ok)throw new Error('Drive save '+r.status);if(showToast)notify('Fournisseurs sauvegardés sur Google Drive.');return true}catch(e){console.error(e);if(showToast)notify('Sauvegarde Google Drive impossible.');return false}}
async function loadFromDriveIfNewer(){if(!googleAccessToken)return false;try{const file=(await driveList())[0];if(!file)return false;const r=await fetch(`https://www.googleapis.com/drive/v3/files/${file.id}?alt=media`,{headers:{Authorization:`Bearer ${googleAccessToken}`}});if(!r.ok)return false;const remote=normalizeData(await r.json());if(data.suppliers.length&&String(remote.updatedAt||'')<=String(data.updatedAt||''))return false;data=remote;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));selectedSupplierId='';renderAll();return true}catch(e){console.warn(e);return false}}
window.addEventListener('message',async e=>{if(location.origin&&location.origin!=='null'&&e.origin!==location.origin)return;const m=e.data||{};if(m.type==='BASTCOMPTA_GOOGLE_TOKEN'){googleAccessToken=m.accessToken||null;setDriveState(!!googleAccessToken);if(googleAccessToken)await loadFromDriveIfNewer()}if(m.type==='BASTCOMPTA_GOOGLE_LOGOUT'){googleAccessToken=null;setDriveState(false)}})
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){data=loadData();renderAll()}})
async function saveFromPortalGlobal(){saveLocal('Sauvegarde globale Fournisseurs');const drive=googleAccessToken?await saveSyncToDrive(false):false;return{ok:true,module:'fournisseurs',local:true,drive:!!drive}}
window.BastComptaModule={name:'Fournisseurs',save:saveFromPortalGlobal,saveData:saveFromPortalGlobal,getChangeSnapshot:()=>data,getStatus:()=>({ready:true,module:'fournisseurs'})};
setDriveState(false);renderAll();safePostToParent({type:'BASTCOMPTA_DRIVE_STATUS_REQUEST'});
